# Generated by Django 5.2.15 on 2026-06-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['-timestamp'], name='inventory_i_timesta_5ca7ad_idx'),
        ),
    ]
